spring.application.name=m4_ss10_demo_session_cookie_appShoppingCart

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/m4_ss10_demo_session_cookie_appshoppingcart?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=19052005
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update